spring.application.name=gym.api
# URL de conexión JDBC (usando tus datos)
spring.datasource.url=jdbc:postgresql://db.gorddzvcftvlxydwxkgo.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Gymrats123$

# Driver y Dialecto
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Magia de Spring: Crea las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de IntelliJ lo que Java le dice a la BD
spring.jpa.show-sql=true
spring.jpa.format_sql=true